// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: movie.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetShowtimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowtimeRequest) Reset() {
	*x = GetShowtimeRequest{}
	mi := &file_movie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowtimeRequest) ProtoMessage() {}

func (x *GetShowtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowtimeRequest.ProtoReflect.Descriptor instead.
func (*GetShowtimeRequest) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{0}
}

func (x *GetShowtimeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetShowtimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ShowtimeData          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowtimeResponse) Reset() {
	*x = GetShowtimeResponse{}
	mi := &file_movie_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowtimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowtimeResponse) ProtoMessage() {}

func (x *GetShowtimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowtimeResponse.ProtoReflect.Descriptor instead.
func (*GetShowtimeResponse) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{1}
}

func (x *GetShowtimeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetShowtimeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetShowtimeResponse) GetData() *ShowtimeData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetShowtimesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowtimesRequest) Reset() {
	*x = GetShowtimesRequest{}
	mi := &file_movie_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowtimesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowtimesRequest) ProtoMessage() {}

func (x *GetShowtimesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowtimesRequest.ProtoReflect.Descriptor instead.
func (*GetShowtimesRequest) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{2}
}

func (x *GetShowtimesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetShowtimesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ShowtimeData        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowtimesResponse) Reset() {
	*x = GetShowtimesResponse{}
	mi := &file_movie_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowtimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowtimesResponse) ProtoMessage() {}

func (x *GetShowtimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowtimesResponse.ProtoReflect.Descriptor instead.
func (*GetShowtimesResponse) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{3}
}

func (x *GetShowtimesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetShowtimesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetShowtimesResponse) GetData() []*ShowtimeData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ShowtimeData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MovieId         string                 `protobuf:"bytes,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	RoomId          string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ShowtimeDate    string                 `protobuf:"bytes,4,opt,name=showtime_date,json=showtimeDate,proto3" json:"showtime_date,omitempty"`
	ShowtimeTime    string                 `protobuf:"bytes,5,opt,name=showtime_time,json=showtimeTime,proto3" json:"showtime_time,omitempty"`
	MovieTitle      string                 `protobuf:"bytes,6,opt,name=movie_title,json=movieTitle,proto3" json:"movie_title,omitempty"`
	RoomNumber      string                 `protobuf:"bytes,7,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	SeatNumbers     []string               `protobuf:"bytes,8,rep,name=seat_numbers,json=seatNumbers,proto3" json:"seat_numbers,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,9,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShowtimeData) Reset() {
	*x = ShowtimeData{}
	mi := &file_movie_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowtimeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowtimeData) ProtoMessage() {}

func (x *ShowtimeData) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowtimeData.ProtoReflect.Descriptor instead.
func (*ShowtimeData) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{4}
}

func (x *ShowtimeData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShowtimeData) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *ShowtimeData) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ShowtimeData) GetShowtimeDate() string {
	if x != nil {
		return x.ShowtimeDate
	}
	return ""
}

func (x *ShowtimeData) GetShowtimeTime() string {
	if x != nil {
		return x.ShowtimeTime
	}
	return ""
}

func (x *ShowtimeData) GetMovieTitle() string {
	if x != nil {
		return x.MovieTitle
	}
	return ""
}

func (x *ShowtimeData) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *ShowtimeData) GetSeatNumbers() []string {
	if x != nil {
		return x.SeatNumbers
	}
	return nil
}

func (x *ShowtimeData) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type GetSeatsWithPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowtimeId    string                 `protobuf:"bytes,1,opt,name=showtime_id,json=showtimeId,proto3" json:"showtime_id,omitempty"`
	SeatIds       []string               `protobuf:"bytes,2,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatsWithPriceRequest) Reset() {
	*x = GetSeatsWithPriceRequest{}
	mi := &file_movie_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatsWithPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatsWithPriceRequest) ProtoMessage() {}

func (x *GetSeatsWithPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatsWithPriceRequest.ProtoReflect.Descriptor instead.
func (*GetSeatsWithPriceRequest) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{5}
}

func (x *GetSeatsWithPriceRequest) GetShowtimeId() string {
	if x != nil {
		return x.ShowtimeId
	}
	return ""
}

func (x *GetSeatsWithPriceRequest) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

type GetSeatsWithPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*SeatPriceData       `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatsWithPriceResponse) Reset() {
	*x = GetSeatsWithPriceResponse{}
	mi := &file_movie_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatsWithPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatsWithPriceResponse) ProtoMessage() {}

func (x *GetSeatsWithPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatsWithPriceResponse.ProtoReflect.Descriptor instead.
func (*GetSeatsWithPriceResponse) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{6}
}

func (x *GetSeatsWithPriceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSeatsWithPriceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSeatsWithPriceResponse) GetData() []*SeatPriceData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetSeatsWithPriceResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type SeatPriceData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        string                 `protobuf:"bytes,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	SeatNumber    string                 `protobuf:"bytes,2,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	SeatType      string                 `protobuf:"bytes,3,opt,name=seat_type,json=seatType,proto3" json:"seat_type,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Available     bool                   `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	SeatRow       string                 `protobuf:"bytes,6,opt,name=seat_row,json=seatRow,proto3" json:"seat_row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatPriceData) Reset() {
	*x = SeatPriceData{}
	mi := &file_movie_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatPriceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatPriceData) ProtoMessage() {}

func (x *SeatPriceData) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatPriceData.ProtoReflect.Descriptor instead.
func (*SeatPriceData) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{7}
}

func (x *SeatPriceData) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *SeatPriceData) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *SeatPriceData) GetSeatType() string {
	if x != nil {
		return x.SeatType
	}
	return ""
}

func (x *SeatPriceData) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SeatPriceData) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *SeatPriceData) GetSeatRow() string {
	if x != nil {
		return x.SeatRow
	}
	return ""
}

type GetSeatDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatIds       []string               `protobuf:"bytes,1,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatDetailsRequest) Reset() {
	*x = GetSeatDetailsRequest{}
	mi := &file_movie_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatDetailsRequest) ProtoMessage() {}

func (x *GetSeatDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetSeatDetailsRequest) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{8}
}

func (x *GetSeatDetailsRequest) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

type GetSeatDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*SeatDetailData      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatDetailsResponse) Reset() {
	*x = GetSeatDetailsResponse{}
	mi := &file_movie_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatDetailsResponse) ProtoMessage() {}

func (x *GetSeatDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetSeatDetailsResponse) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{9}
}

func (x *GetSeatDetailsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSeatDetailsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSeatDetailsResponse) GetData() []*SeatDetailData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SeatDetailData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        string                 `protobuf:"bytes,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	SeatRow       string                 `protobuf:"bytes,2,opt,name=seat_row,json=seatRow,proto3" json:"seat_row,omitempty"`
	SeatNumber    int32                  `protobuf:"varint,3,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	SeatType      string                 `protobuf:"bytes,4,opt,name=seat_type,json=seatType,proto3" json:"seat_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatDetailData) Reset() {
	*x = SeatDetailData{}
	mi := &file_movie_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatDetailData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatDetailData) ProtoMessage() {}

func (x *SeatDetailData) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatDetailData.ProtoReflect.Descriptor instead.
func (*SeatDetailData) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{10}
}

func (x *SeatDetailData) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *SeatDetailData) GetSeatRow() string {
	if x != nil {
		return x.SeatRow
	}
	return ""
}

func (x *SeatDetailData) GetSeatNumber() int32 {
	if x != nil {
		return x.SeatNumber
	}
	return 0
}

func (x *SeatDetailData) GetSeatType() string {
	if x != nil {
		return x.SeatType
	}
	return ""
}

var File_movie_proto protoreflect.FileDescriptor

const file_movie_proto_rawDesc = "" +
	"\n" +
	"\vmovie.proto\x12\x02pb\"$\n" +
	"\x12GetShowtimeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"o\n" +
	"\x13GetShowtimeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x04data\x18\x03 \x01(\v2\x10.pb.ShowtimeDataR\x04data\"'\n" +
	"\x13GetShowtimesRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"p\n" +
	"\x14GetShowtimesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x04data\x18\x03 \x03(\v2\x10.pb.ShowtimeDataR\x04data\"\xac\x02\n" +
	"\fShowtimeData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\tR\amovieId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12#\n" +
	"\rshowtime_date\x18\x04 \x01(\tR\fshowtimeDate\x12#\n" +
	"\rshowtime_time\x18\x05 \x01(\tR\fshowtimeTime\x12\x1f\n" +
	"\vmovie_title\x18\x06 \x01(\tR\n" +
	"movieTitle\x12\x1f\n" +
	"\vroom_number\x18\a \x01(\tR\n" +
	"roomNumber\x12!\n" +
	"\fseat_numbers\x18\b \x03(\tR\vseatNumbers\x12)\n" +
	"\x10duration_seconds\x18\t \x01(\x03R\x0fdurationSeconds\"V\n" +
	"\x18GetSeatsWithPriceRequest\x12\x1f\n" +
	"\vshowtime_id\x18\x01 \x01(\tR\n" +
	"showtimeId\x12\x19\n" +
	"\bseat_ids\x18\x02 \x03(\tR\aseatIds\"\x99\x01\n" +
	"\x19GetSeatsWithPriceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x04data\x18\x03 \x03(\v2\x11.pb.SeatPriceDataR\x04data\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\"\xb5\x01\n" +
	"\rSeatPriceData\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\tR\x06seatId\x12\x1f\n" +
	"\vseat_number\x18\x02 \x01(\tR\n" +
	"seatNumber\x12\x1b\n" +
	"\tseat_type\x18\x03 \x01(\tR\bseatType\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\bR\tavailable\x12\x19\n" +
	"\bseat_row\x18\x06 \x01(\tR\aseatRow\"2\n" +
	"\x15GetSeatDetailsRequest\x12\x19\n" +
	"\bseat_ids\x18\x01 \x03(\tR\aseatIds\"t\n" +
	"\x16GetSeatDetailsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x03 \x03(\v2\x12.pb.SeatDetailDataR\x04data\"\x82\x01\n" +
	"\x0eSeatDetailData\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\tR\x06seatId\x12\x19\n" +
	"\bseat_row\x18\x02 \x01(\tR\aseatRow\x12\x1f\n" +
	"\vseat_number\x18\x03 \x01(\x05R\n" +
	"seatNumber\x12\x1b\n" +
	"\tseat_type\x18\x04 \x01(\tR\bseatType2\xac\x02\n" +
	"\fMovieService\x12>\n" +
	"\vGetShowtime\x12\x16.pb.GetShowtimeRequest\x1a\x17.pb.GetShowtimeResponse\x12A\n" +
	"\fGetShowtimes\x12\x17.pb.GetShowtimesRequest\x1a\x18.pb.GetShowtimesResponse\x12P\n" +
	"\x11GetSeatsWithPrice\x12\x1c.pb.GetSeatsWithPriceRequest\x1a\x1d.pb.GetSeatsWithPriceResponse\x12G\n" +
	"\x0eGetSeatDetails\x12\x19.pb.GetSeatDetailsRequest\x1a\x1a.pb.GetSeatDetailsResponseB\x18Z\x16movie-service/proto/pbb\x06proto3"

var (
	file_movie_proto_rawDescOnce sync.Once
	file_movie_proto_rawDescData []byte
)

func file_movie_proto_rawDescGZIP() []byte {
	file_movie_proto_rawDescOnce.Do(func() {
		file_movie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_movie_proto_rawDesc), len(file_movie_proto_rawDesc)))
	})
	return file_movie_proto_rawDescData
}

var file_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_movie_proto_goTypes = []any{
	(*GetShowtimeRequest)(nil),        // 0: pb.GetShowtimeRequest
	(*GetShowtimeResponse)(nil),       // 1: pb.GetShowtimeResponse
	(*GetShowtimesRequest)(nil),       // 2: pb.GetShowtimesRequest
	(*GetShowtimesResponse)(nil),      // 3: pb.GetShowtimesResponse
	(*ShowtimeData)(nil),              // 4: pb.ShowtimeData
	(*GetSeatsWithPriceRequest)(nil),  // 5: pb.GetSeatsWithPriceRequest
	(*GetSeatsWithPriceResponse)(nil), // 6: pb.GetSeatsWithPriceResponse
	(*SeatPriceData)(nil),             // 7: pb.SeatPriceData
	(*GetSeatDetailsRequest)(nil),     // 8: pb.GetSeatDetailsRequest
	(*GetSeatDetailsResponse)(nil),    // 9: pb.GetSeatDetailsResponse
	(*SeatDetailData)(nil),            // 10: pb.SeatDetailData
}
var file_movie_proto_depIdxs = []int32{
	4,  // 0: pb.GetShowtimeResponse.data:type_name -> pb.ShowtimeData
	4,  // 1: pb.GetShowtimesResponse.data:type_name -> pb.ShowtimeData
	7,  // 2: pb.GetSeatsWithPriceResponse.data:type_name -> pb.SeatPriceData
	10, // 3: pb.GetSeatDetailsResponse.data:type_name -> pb.SeatDetailData
	0,  // 4: pb.MovieService.GetShowtime:input_type -> pb.GetShowtimeRequest
	2,  // 5: pb.MovieService.GetShowtimes:input_type -> pb.GetShowtimesRequest
	5,  // 6: pb.MovieService.GetSeatsWithPrice:input_type -> pb.GetSeatsWithPriceRequest
	8,  // 7: pb.MovieService.GetSeatDetails:input_type -> pb.GetSeatDetailsRequest
	1,  // 8: pb.MovieService.GetShowtime:output_type -> pb.GetShowtimeResponse
	3,  // 9: pb.MovieService.GetShowtimes:output_type -> pb.GetShowtimesResponse
	6,  // 10: pb.MovieService.GetSeatsWithPrice:output_type -> pb.GetSeatsWithPriceResponse
	9,  // 11: pb.MovieService.GetSeatDetails:output_type -> pb.GetSeatDetailsResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_movie_proto_init() }
func file_movie_proto_init() {
	if File_movie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_movie_proto_rawDesc), len(file_movie_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_movie_proto_goTypes,
		DependencyIndexes: file_movie_proto_depIdxs,
		MessageInfos:      file_movie_proto_msgTypes,
	}.Build()
	File_movie_proto = out.File
	file_movie_proto_goTypes = nil
	file_movie_proto_depIdxs = nil
}
