// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: movie.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetShowtimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowtimeRequest) Reset() {
	*x = GetShowtimeRequest{}
	mi := &file_movie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowtimeRequest) ProtoMessage() {}

func (x *GetShowtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowtimeRequest.ProtoReflect.Descriptor instead.
func (*GetShowtimeRequest) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{0}
}

func (x *GetShowtimeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetShowtimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ShowtimeData          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowtimeResponse) Reset() {
	*x = GetShowtimeResponse{}
	mi := &file_movie_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowtimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowtimeResponse) ProtoMessage() {}

func (x *GetShowtimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowtimeResponse.ProtoReflect.Descriptor instead.
func (*GetShowtimeResponse) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{1}
}

func (x *GetShowtimeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetShowtimeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetShowtimeResponse) GetData() *ShowtimeData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetShowtimesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowtimesRequest) Reset() {
	*x = GetShowtimesRequest{}
	mi := &file_movie_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowtimesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowtimesRequest) ProtoMessage() {}

func (x *GetShowtimesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowtimesRequest.ProtoReflect.Descriptor instead.
func (*GetShowtimesRequest) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{2}
}

func (x *GetShowtimesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetShowtimesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ShowtimeData        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowtimesResponse) Reset() {
	*x = GetShowtimesResponse{}
	mi := &file_movie_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowtimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowtimesResponse) ProtoMessage() {}

func (x *GetShowtimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowtimesResponse.ProtoReflect.Descriptor instead.
func (*GetShowtimesResponse) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{3}
}

func (x *GetShowtimesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetShowtimesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetShowtimesResponse) GetData() []*ShowtimeData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ShowtimeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MovieId       string                 `protobuf:"bytes,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ShowtimeDate  string                 `protobuf:"bytes,4,opt,name=showtime_date,json=showtimeDate,proto3" json:"showtime_date,omitempty"`
	ShowtimeTime  string                 `protobuf:"bytes,5,opt,name=showtime_time,json=showtimeTime,proto3" json:"showtime_time,omitempty"`
	MovieTitle    string                 `protobuf:"bytes,6,opt,name=movie_title,json=movieTitle,proto3" json:"movie_title,omitempty"`
	RoomNumber    string                 `protobuf:"bytes,7,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	SeatNumbers   []string               `protobuf:"bytes,8,rep,name=seat_numbers,json=seatNumbers,proto3" json:"seat_numbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowtimeData) Reset() {
	*x = ShowtimeData{}
	mi := &file_movie_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowtimeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowtimeData) ProtoMessage() {}

func (x *ShowtimeData) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowtimeData.ProtoReflect.Descriptor instead.
func (*ShowtimeData) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{4}
}

func (x *ShowtimeData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShowtimeData) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *ShowtimeData) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ShowtimeData) GetShowtimeDate() string {
	if x != nil {
		return x.ShowtimeDate
	}
	return ""
}

func (x *ShowtimeData) GetShowtimeTime() string {
	if x != nil {
		return x.ShowtimeTime
	}
	return ""
}

func (x *ShowtimeData) GetMovieTitle() string {
	if x != nil {
		return x.MovieTitle
	}
	return ""
}

func (x *ShowtimeData) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *ShowtimeData) GetSeatNumbers() []string {
	if x != nil {
		return x.SeatNumbers
	}
	return nil
}

var File_movie_proto protoreflect.FileDescriptor

const file_movie_proto_rawDesc = "" +
	"\n" +
	"\vmovie.proto\x12\x02pb\"$\n" +
	"\x12GetShowtimeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"o\n" +
	"\x13GetShowtimeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x04data\x18\x03 \x01(\v2\x10.pb.ShowtimeDataR\x04data\"'\n" +
	"\x13GetShowtimesRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"p\n" +
	"\x14GetShowtimesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x04data\x18\x03 \x03(\v2\x10.pb.ShowtimeDataR\x04data\"\x81\x02\n" +
	"\fShowtimeData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\tR\amovieId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12#\n" +
	"\rshowtime_date\x18\x04 \x01(\tR\fshowtimeDate\x12#\n" +
	"\rshowtime_time\x18\x05 \x01(\tR\fshowtimeTime\x12\x1f\n" +
	"\vmovie_title\x18\x06 \x01(\tR\n" +
	"movieTitle\x12\x1f\n" +
	"\vroom_number\x18\a \x01(\tR\n" +
	"roomNumber\x12!\n" +
	"\fseat_numbers\x18\b \x03(\tR\vseatNumbers2\x91\x01\n" +
	"\fMovieService\x12>\n" +
	"\vGetShowtime\x12\x16.pb.GetShowtimeRequest\x1a\x17.pb.GetShowtimeResponse\x12A\n" +
	"\fGetShowtimes\x12\x17.pb.GetShowtimesRequest\x1a\x18.pb.GetShowtimesResponseB\x18Z\x16movie-service/proto/pbb\x06proto3"

var (
	file_movie_proto_rawDescOnce sync.Once
	file_movie_proto_rawDescData []byte
)

func file_movie_proto_rawDescGZIP() []byte {
	file_movie_proto_rawDescOnce.Do(func() {
		file_movie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_movie_proto_rawDesc), len(file_movie_proto_rawDesc)))
	})
	return file_movie_proto_rawDescData
}

var file_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_movie_proto_goTypes = []any{
	(*GetShowtimeRequest)(nil),   // 0: pb.GetShowtimeRequest
	(*GetShowtimeResponse)(nil),  // 1: pb.GetShowtimeResponse
	(*GetShowtimesRequest)(nil),  // 2: pb.GetShowtimesRequest
	(*GetShowtimesResponse)(nil), // 3: pb.GetShowtimesResponse
	(*ShowtimeData)(nil),         // 4: pb.ShowtimeData
}
var file_movie_proto_depIdxs = []int32{
	4, // 0: pb.GetShowtimeResponse.data:type_name -> pb.ShowtimeData
	4, // 1: pb.GetShowtimesResponse.data:type_name -> pb.ShowtimeData
	0, // 2: pb.MovieService.GetShowtime:input_type -> pb.GetShowtimeRequest
	2, // 3: pb.MovieService.GetShowtimes:input_type -> pb.GetShowtimesRequest
	1, // 4: pb.MovieService.GetShowtime:output_type -> pb.GetShowtimeResponse
	3, // 5: pb.MovieService.GetShowtimes:output_type -> pb.GetShowtimesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_movie_proto_init() }
func file_movie_proto_init() {
	if File_movie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_movie_proto_rawDesc), len(file_movie_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_movie_proto_goTypes,
		DependencyIndexes: file_movie_proto_depIdxs,
		MessageInfos:      file_movie_proto_msgTypes,
	}.Build()
	File_movie_proto = out.File
	file_movie_proto_goTypes = nil
	file_movie_proto_depIdxs = nil
}
