// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: outbox.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOutboxEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOutboxEventRequest) Reset() {
	*x = CreateOutboxEventRequest{}
	mi := &file_outbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOutboxEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOutboxEventRequest) ProtoMessage() {}

func (x *CreateOutboxEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOutboxEventRequest.ProtoReflect.Descriptor instead.
func (*CreateOutboxEventRequest) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOutboxEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *CreateOutboxEventRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type CreateOutboxEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	EventId       int32                  `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOutboxEventResponse) Reset() {
	*x = CreateOutboxEventResponse{}
	mi := &file_outbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOutboxEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOutboxEventResponse) ProtoMessage() {}

func (x *CreateOutboxEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOutboxEventResponse.ProtoReflect.Descriptor instead.
func (*CreateOutboxEventResponse) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOutboxEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateOutboxEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateOutboxEventResponse) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

var File_outbox_proto protoreflect.FileDescriptor

const file_outbox_proto_rawDesc = "" +
	"\n" +
	"\foutbox.proto\x12\x02pb\"S\n" +
	"\x18CreateOutboxEventRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"j\n" +
	"\x19CreateOutboxEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\x05R\aeventId2a\n" +
	"\rOutboxService\x12P\n" +
	"\x11CreateOutboxEvent\x12\x1c.pb.CreateOutboxEventRequest\x1a\x1d.pb.CreateOutboxEventResponseB\x19Z\x17worker-service/proto/pbb\x06proto3"

var (
	file_outbox_proto_rawDescOnce sync.Once
	file_outbox_proto_rawDescData []byte
)

func file_outbox_proto_rawDescGZIP() []byte {
	file_outbox_proto_rawDescOnce.Do(func() {
		file_outbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outbox_proto_rawDesc), len(file_outbox_proto_rawDesc)))
	})
	return file_outbox_proto_rawDescData
}

var file_outbox_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_outbox_proto_goTypes = []any{
	(*CreateOutboxEventRequest)(nil),  // 0: pb.CreateOutboxEventRequest
	(*CreateOutboxEventResponse)(nil), // 1: pb.CreateOutboxEventResponse
}
var file_outbox_proto_depIdxs = []int32{
	0, // 0: pb.OutboxService.CreateOutboxEvent:input_type -> pb.CreateOutboxEventRequest
	1, // 1: pb.OutboxService.CreateOutboxEvent:output_type -> pb.CreateOutboxEventResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_outbox_proto_init() }
func file_outbox_proto_init() {
	if File_outbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outbox_proto_rawDesc), len(file_outbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_outbox_proto_goTypes,
		DependencyIndexes: file_outbox_proto_depIdxs,
		MessageInfos:      file_outbox_proto_msgTypes,
	}.Build()
	File_outbox_proto = out.File
	file_outbox_proto_goTypes = nil
	file_outbox_proto_depIdxs = nil
}
